# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/statsig/all/statsig.rbi
#
# statsig-1.16.2

module Statsig
  def self.check_gate(*args, **, &blk); end
  def self.ensure_initialized; end
  def self.get_client_initialize_response(*args, **, &blk); end
  def self.get_config(*args, **, &blk); end
  def self.get_experiment(*args, **, &blk); end
  def self.get_layer(*args, **, &blk); end
  def self.get_statsig_metadata(*args, **, &blk); end
  def self.initialize(*args, **, &blk); end
  def self.log_event(*args, **, &blk); end
  def self.override_config(*args, **, &blk); end
  def self.override_gate(*args, **, &blk); end
  def self.shutdown(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
