Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false